@hostaddress = http://localhost:5127
###
GET {{hostaddress}}/stat/viewer
Accept: application/json
###
###
POST {{hostaddress}}/canvas/draw
Content-Type: application/json

{
  "pixels": [
    { "x": 1, "y": 2, "color": "red" },
    { "x": 3, "y": 4, "color": "blue" }
  ]
}
###
GET {{hostaddress}}/canvas/data
Accept: application/json
###
GET {{hostaddress}}/chat/join
Accept: application/json

HAL
###
POST {{hostaddress}}/chat/send
Content-Type: text/plain

HAL
###
DELETE {{hostaddress}}/chat/leave
Content-Type: text/plain

HAL
###
GET {{hostaddress}}/chat/join
Accept: application/json

NEW
###